export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_ERROR = 'FETCH_CHAT_ERROR';

export const FETCH_CURRENT_CHAT_REQUEST = 'FETCH_CURRENT_CHAT_REQUEST';
export const FETCH_CURRENT_CHAT_SUCCESS = 'FETCH_CURRENT_CHAT_SUCCESS';
export const FETCH_CURRENT_CHAT_ERROR = 'FETCH_CURRENT_CHAT_ERROR';
